// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: MatMADNESS (https://sketchfab.com/matmadnessart)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/among-us-astronaut-clay-20b591de51eb4fc3a4c5a4d40c6011d5
// Title: Among Us Astronaut - Clay
// */

// import { useAnimations, useGLTF } from '@react-three/drei'
// import { useEffect, useRef } from 'react'
// export default function Astronaut(props) {
//     const { nodes, materials, animations } = useGLTF('/models/among_us_astronaut_-_clay.glb')
//     const group = useRef()
//     const { actions } = useAnimations(animations, group)
//     useEffect(()=>{
//         if(animations.length>0){
//             actions[animations[0].name]?.play()
//         }
//     })
//     return (
//         <group ref={group} {...props} dispose={null}>
//             <mesh
//                 castShadow
//                 receiveShadow
//                 geometry={nodes.Object_2.geometry}
//                 material={materials['Material.002']}
//                 rotation={[-Math.PI / 2, 0, 0]}
//                 scale={2.5}
//             />
//         </group>
//     )
// }

// // useGLTF.preload('/models/among_us_astronaut_-_clay.glb')


import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/among_us_character (1).glb')
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        if (animations.length > 0) {
            actions[animations[0].name]?.play()
        }
    }, [actions, animations])
    return (
        <group
            ref={group}
            {...props}
            dispose={null}
            scale={props.scale || .05}
            position={props.position||[8.115, -2, -9.454]}
            rotation={[-Math.PI / 2, 0, Math.PI]}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"

                >
                    <group name="b3faf779fc144613abde2c91592dd257fbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="Box001"
                                    position={[1.557, 75.821, -11.173]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                />
                                <group name="Foot" position={[1.557, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                                    <group name="Object_6">
                                        <primitive object={nodes._rootJoint} />
                                        <skinnedMesh
                                            name="Object_9"
                                            geometry={nodes.Object_9.geometry}
                                            material={materials['Scene_-_Root']}
                                            skeleton={nodes.Object_9.skeleton}
                                            scale={2.5}
                                        />
                                        <group
                                            name="Object_8"
                                            position={[1.557, 35.589, 7.398]}
                                            rotation={[-Math.PI / 2, 0, 0]}
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/among_us_character (1).glb')
